/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export type EscrowUserStruct = {
  userAddress: PromiseOrValue<string>;
  userType: PromiseOrValue<BigNumberish>;
  amount: PromiseOrValue<BigNumberish>;
};

export type EscrowUserStructOutput = [string, number, BigNumber] & {
  userAddress: string;
  userType: number;
  amount: BigNumber;
};

export interface RulesLibInterface extends utils.Interface {
  functions: {
    "checkForUserConflict((address,uint8,uint256)[],address,uint8,uint256,bool)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "checkForUserConflict"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "checkForUserConflict",
    values: [
      EscrowUserStruct[],
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkForUserConflict",
    data: BytesLike
  ): Result;

  events: {};
}

export interface RulesLib extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RulesLibInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    checkForUserConflict(
      users: EscrowUserStruct[],
      userAddress: PromiseOrValue<string>,
      userType: PromiseOrValue<BigNumberish>,
      userIndex: PromiseOrValue<BigNumberish>,
      checkAll: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[void]>;
  };

  checkForUserConflict(
    users: EscrowUserStruct[],
    userAddress: PromiseOrValue<string>,
    userType: PromiseOrValue<BigNumberish>,
    userIndex: PromiseOrValue<BigNumberish>,
    checkAll: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    checkForUserConflict(
      users: EscrowUserStruct[],
      userAddress: PromiseOrValue<string>,
      userType: PromiseOrValue<BigNumberish>,
      userIndex: PromiseOrValue<BigNumberish>,
      checkAll: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    checkForUserConflict(
      users: EscrowUserStruct[],
      userAddress: PromiseOrValue<string>,
      userType: PromiseOrValue<BigNumberish>,
      userIndex: PromiseOrValue<BigNumberish>,
      checkAll: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    checkForUserConflict(
      users: EscrowUserStruct[],
      userAddress: PromiseOrValue<string>,
      userType: PromiseOrValue<BigNumberish>,
      userIndex: PromiseOrValue<BigNumberish>,
      checkAll: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
